name: deploy

on:
  push:
    branches: [ 'main' ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mobiledevops/secret-to-file-action@v1
        with:
          base64-encoded-secret: ${{ secrets.CONFIG_YAML }}
          filename: "config.yaml"
          is-executable: false
          working-directory: "./"
      - uses: mobiledevops/secret-to-file-action@v1
        with:
          base64-encoded-secret: ${{ secrets.CONFIG_ATLASNET_YAML }}
          filename: "config-atlasnet.yaml"
          is-executable: false
          working-directory: "./"
      - uses: mobiledevops/secret-to-file-action@v1
        with:
          base64-encoded-secret: ${{ secrets.ID_JSON }}
          filename: "id.json"
          is-executable: false
          working-directory: "./"
      - uses: ./.github/actions/release
        with:
          repository: "artifacts-0"
          project-name: "atlasnet"
          app-name: "ping"
          gcp-auth-key: ${{ secrets.GCP_AUTH_KEY }}

  deploy-test:
    needs: [ release ]
    uses: ./.github/workflows/deploy-app.yml
    with:
      environment: 'test'
    secrets: inherit
